openapi: 3.0.0
info:
  title: Mini Twitter API
  version: 0.1.0

paths:
  /users:
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
  /users/{id}:
    get:
      summary: Get user by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Not Found
        '400':
          description: Bad Request
components:
  schemas:
    NewUserRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
    UserResponse:
      type: object
      required: [id, username]
      properties:
        id:
          type: integer
        username:
          type: string
